# These are supported funding model platforms for GitHub Sponsors button
github: [angganzcool]
custom:
  - https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-63C1163027265553ANKGZKEI
  - https://saweria.co/
  - https://buymeacoffee.com/
